version: '3.9'

services:
  postgres:
    container_name: postgres-db
    build:
      context: ./db
    env_file:
      - ./db/.env
    ports:
      - 5432:5432
    networks:
      - database
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    networks:
      - database
      - database_admin
    depends_on:
      - postgres

networks:
  database:
    driver: bridge

  database_admin:
    driver: bridge
